server:
  port: 8121

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: hayzt.cn:8848
        username: nacos
        password: nacos

    gateway:
      routes:
        - id: test-service-route
          uri: lb://test-service
          predicates:
            - Path=/test/**
      discovery:
        locator:
          # 是否与服务发现组件进行结合，通过serviceId转发到具体服务实例
          enabled: true #是否开启基于服务发现的路由规则
          lower-case-service-id: true #是否将服务名称转换小写
