server:
  port: 8130

spring:
  application:
    name: kafka-producer

  kafka:
    bootstrap-servers: hayzt.cn:9092
    producer: # producer 生产者
      retries: 0 # 重试次数
      acks: 1 # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384 # 批量大小
      buffer-memory: 33554432 # 生产端缓冲区大小
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer